//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JavadocParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Eir.JavaDocParser.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="JavadocParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IJavadocParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.documentation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocumentation([NotNull] JavadocParser.DocumentationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.documentationContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocumentationContent([NotNull] JavadocParser.DocumentationContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.skipWhitespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkipWhitespace([NotNull] JavadocParser.SkipWhitespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescription([NotNull] JavadocParser.DescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.descriptionLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescriptionLine([NotNull] JavadocParser.DescriptionLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.descriptionLineStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescriptionLineStart([NotNull] JavadocParser.DescriptionLineStartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.descriptionLineNoSpaceNoAt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescriptionLineNoSpaceNoAt([NotNull] JavadocParser.DescriptionLineNoSpaceNoAtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.descriptionLineElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescriptionLineElement([NotNull] JavadocParser.DescriptionLineElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.descriptionLineText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescriptionLineText([NotNull] JavadocParser.DescriptionLineTextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.descriptionNewline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescriptionNewline([NotNull] JavadocParser.DescriptionNewlineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.tagSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTagSection([NotNull] JavadocParser.TagSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.blockTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockTag([NotNull] JavadocParser.BlockTagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.blockTagName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockTagName([NotNull] JavadocParser.BlockTagNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.blockTagContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockTagContent([NotNull] JavadocParser.BlockTagContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.blockTagText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockTagText([NotNull] JavadocParser.BlockTagTextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.blockTagTextElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockTagTextElement([NotNull] JavadocParser.BlockTagTextElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.inlineTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineTag([NotNull] JavadocParser.InlineTagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.inlineTagName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineTagName([NotNull] JavadocParser.InlineTagNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.inlineTagContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineTagContent([NotNull] JavadocParser.InlineTagContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.braceExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBraceExpression([NotNull] JavadocParser.BraceExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.braceContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBraceContent([NotNull] JavadocParser.BraceContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavadocParser.braceText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBraceText([NotNull] JavadocParser.BraceTextContext context);
}
} // namespace Eir.JavaDocParser.Parser
